name: Testing

on:
  push:
    branches:
      - main
 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Add bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.0.11

    - name: Install Dependencies
      run: bun i

    - name: Testing
      run: bun run test
