name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        credentials_json: ${{ secrets.AUTH_KEY }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'
    - name: Print Environment Variables
      run: |
        echo DB_HOST=${{ secrets.DB_HOST }}
        echo DB_USER=${{ secrets.DB_USER }}
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        echo DB_NAME=${{ secrets.DB_NAME }}
        echo DB_PORT=${{ secrets.DB_PORT }}

    - name: Install Dependencies
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: bun install

    - name: Run Tests
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: bun run test

    - name: Build
      run: bun build
